data:
  raw_train_dir: "/kaggle/input/siim-acr-pneumothorax-segmentation-data/dicom-images-train"
  raw_test_dir: "/kaggle/input/siim-acr-pneumothorax-segmentation-data/dicom-images-test"
  raw_csv_path: "/kaggle/input/siim-acr-pneumothorax-segmentation-data/train-rle.csv"
  dataset_dir: "/kaggle/input/siim-pneumothorax-256-png/pneumo_processed"
  img_height: 256
  img_width: 256
  num_workers: 2

train:
  experiment_name: "exp4_deeplab_aug"
  architecture: "DeepLabV3"
  encoder_name: "resnet50"
  pretrained: true
  batch_size: 8
  epochs: 25
  learning_rate: 0.0001
  pixel_threshold: 20
  
  # WITH AUGMENTATION
  use_augmentation: true
  aug_prob: 0.5
  aug_rotate_limit: 15